    create table tags (
       tool_id integer not null,
        tags varchar2(255 char)
    );
    
    create table w_tool (
       id integer generated by default as identity,
        description varchar2(255 char),
        link varchar2(255 char),
        title varchar2(255 char),
        primary key (id)
    );
    
    alter table tags 
       add constraint FK_tags 
       foreign key (tool_id) 
       references w_tool;